version: '3'

services:
  mongo:
    container_name: store_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  server:
    container_name: store_item_server
    build:
      context: itemserver
    ports:
      - "4000:4000"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  mongo_login:
    container_name: login_db
    image: mongo
    restart: always
    command: mongod --port 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27018:27017"
  login:
    container_name: store_login_server
    depends_on:
      - mongo_login
    build:
      context: loginserver
    ports:
      - "4001:4001"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  client:
    container_name: store_client
    restart: always
    environment:
      - GRAPHQL_SERVER_URL=127.0.0.1:4000
    build:
      context: client
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"


