version: '3'

services:
  mongo:
    container_name: store_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  server:
    container_name: store_server
    build:
      context: graphql
    ports:
      - "4000:4000"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  client:
    container_name: store_client
    restart: always
    env_file:
      - ./.env
    environment:
      - GRAPHQL_URL=192.168.99.101:4000/graphql
    build:
      context: client
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"

networks:
  network:

volumes:
  db: